### ISSUE TITLE
ModuleNotFoundError: No module named 'make_it_dense.models'

### ISSUE THREAD

**Issue by zxczrx123** [PRBonn/make_it_dense#1]
@nachovizzo 
Hi, Thanks for your great work!
![image](https://user-images.githubusercontent.com/37107333/178191281-a92ba96b-5034-44d0-8eae-2b008d2e3963.png)
I had this problem after a tough environment configuration. Is the code complete?

**Comment by nachovizzo** [comment]
Hello. It looks like you couldn't properly install the python package. What's the output of this command on the terminal?

```sh
$ python3 -c 'import make_it_dense'
```

**Comment by zxczrx123** [comment]
Hi. The problem should be that the 'models' subdirectory is missing so that the 'CompletionNet' cannot be imported.
![image](https://user-images.githubusercontent.com/37107333/179034054-8a56fa11-3aff-48e2-a768-739c7b143b75.png)

I can't find the ‘models’ directory in 'src/make_it_dense'.
![image](https://user-images.githubusercontent.com/37107333/179036044-c37d182c-6842-465e-891e-3a38d7943373.png)

**Comment by nachovizzo** [comment]
@zxczrx123 Thanks a lot! That folder slipped out of my fingers! Sorry
