### ISSUE TITLE
OpenVDB dependencies

### ISSUE THREAD

**Issue by schenock** [PRBonn/make_it_dense#3]
I tried to build OpenVDB dependency as you described, however the build fails due to (I assume) Boost version mismatch. I have default 1.71, tried with 1.73 still I am unable to build your custom fork openvdb.

Did you maybe encounter similar issues?

Btw, do you use any additional lidar info e.g. intensity values or is it just the XYZ coordinates?

Thank you.

**Comment by nachovizzo** [comment]
I haven't encountered this issue myself, could you specify a bit more details about your system?

I'm only using `XYZ` coordinates ;)

**Comment by Gaozhongpai** [comment]
> I tried to build OpenVDB dependency as you described, however the build fails due to (I assume) Boost version mismatch. I have default 1.71, tried with 1.73 still I am unable to build your custom fork openvdb.
> 
> Did you maybe encounter similar issues?
> 
> Btw, do you use any additional lidar info e.g. intensity values or is it just the XYZ coordinates?
> 
> Thank you.

I encountered the same issue before. Your global python version should be python 3.8 so that the Boost.Python will be installed with ptthon38 version. The easier way would be running in a docker.
