### ISSUE TITLE
Can not import pyopenvdb after install

### ISSUE THREAD

**Issue by yininghase** [PRBonn/make_it_dense#5]
Hello, I'd like to ask maybe a stupid question. 

I try to use the openvdb python API in anaconda environment. After running the given command:
git clone https://github.com/nachovizzo/openvdb.git -b nacho/fix_background_inactive \
  && cd openvdb \
  && mkdir build && cd build \
  && cmake -DOPENVDB_BUILD_PYTHON_MODULE=ON -DUSE_NUMPY=ON .. \
  && sudo make -j$(nproc) all install 

It seems to successfully build and install the openvdb. But i can not import pyopenvdb in python. Could you please help me to find out the reason?
 
The installing logs is as follows:

[ 86%] Built target openvdb_static
[ 93%] Built target openvdb_shared
[ 95%] Built target vdb_print
[100%] Built target pyopenvdb
Install the project...
-- Install configuration: "Release"
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/FindBlosc.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/FindJemalloc.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/FindIlmBase.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/FindLog4cplus.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/FindOpenEXR.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/FindOpenVDB.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/FindTBB.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/OpenVDBGLFW3Setup.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/OpenVDBHoudiniSetup.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/OpenVDBMayaSetup.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/cmake/OpenVDB/OpenVDBUtils.cmake
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/libopenvdb.a
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/libopenvdb.so.9.0.1
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/libopenvdb.so.9.0
-- Set runtime path of "/home/stud/may/.local/lib/cmake/OpenVDB//usr/local/lib/libopenvdb.so.9.0.1" to "/usr/local/lib"
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/libopenvdb.so
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/Exceptions.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/Grid.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/Metadata.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/MetaMap.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/openvdb.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/Platform.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/PlatformConfig.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/Types.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/TypeList.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/version.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/io/Archive.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/io/Compression.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/io/DelayedLoadMetadata.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/io/File.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/io/GridDescriptor.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/io/io.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/io/Queue.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/io/Stream.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/io/TempFile.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/BBox.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/ConjGradient.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Coord.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/DDA.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/FiniteDifference.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Half.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/HalfLimits.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/LegacyFrustum.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Maps.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Mat.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Mat3.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Mat4.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Math.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Operators.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Proximity.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/QuantizedUnitVec.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Quat.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Ray.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Stats.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Stencils.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Transform.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Tuple.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Vec2.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Vec3.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/math/Vec4.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/AttributeArray.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/AttributeArrayString.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/AttributeGroup.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/AttributeSet.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/IndexFilter.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/IndexIterator.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointAdvect.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointAttribute.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointConversion.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointCount.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointDataGrid.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointDelete.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointGroup.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointMask.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointMove.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointSample.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointScatter.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/PointStatistics.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/points/StreamCompression.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Activate.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/ChangeBackground.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Clip.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Composite.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Count.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Dense.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/DenseSparseTools.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Diagnostics.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/FastSweeping.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Filter.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/FindActiveValues.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/GridOperators.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/GridTransformer.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Interpolation.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetAdvect.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetFilter.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetFracture.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetMeasure.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetMorph.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetPlatonic.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetRebuild.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetSphere.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetTracker.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/LevelSetUtil.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Mask.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Merge.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/MeshToVolume.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Morphology.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/MultiResGrid.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/NodeVisitor.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/ParticleAtlas.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/ParticlesToLevelSet.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/PointAdvect.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/PointIndexGrid.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/PointPartitioner.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/PointScatter.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/PointsToMask.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/PoissonSolver.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/PotentialFlow.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Prune.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/RayIntersector.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/RayTracer.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/SignedFloodFill.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/Statistics.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/TopologyToLevelSet.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/ValueTransformer.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/VectorTransformer.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/VelocityFields.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/VolumeAdvect.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/VolumeToMesh.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tools/VolumeToSpheres.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/InternalNode.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/Iterator.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/LeafBuffer.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/LeafManager.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/LeafNode.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/LeafNodeBool.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/LeafNodeMask.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/NodeManager.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/NodeUnion.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/RootNode.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/Tree.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/TreeIterator.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/tree/ValueAccessor.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/CpuTimer.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/ExplicitInstantiation.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/Formats.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/logging.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/MapsUtil.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/Name.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/NodeMasks.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/NullInterrupter.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/PagedArray.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/util/Util.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/thread/Threading.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/python3.8/site-packages/pyopenvdb.so
-- Set runtime path of "/home/stud/may/.local/lib/cmake/OpenVDB//usr/local/lib/python3.8/site-packages/pyopenvdb.so" to "/usr/local/lib"
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/include/openvdb/python/pyopenvdb.h
-- Installing: /home/stud/may/.local/lib/cmake/OpenVDB/usr/local/bin/vdb_print
-- Set runtime path of "/home/stud/may/.local/lib/cmake/OpenVDB//usr/local/bin/vdb_print" to "/usr/local/lib"

**Comment by nachovizzo** [comment]
Hello, thanks for the interest in the project.

This is why I don't like conda 😂 it never works for me. 

Fire up a python shell and see if this path can be seen on the path of whatever interpreter conda is giving to you. If you can't see this path, then you can't import it ;) 
home/stud/may/.local/lib/cmake/OpenVDB/usr/local/lib/python3.8/site-packages/pyopenvdb.so
