### ISSUE TITLE
Conversion of VDB Grids to Tensors

### ISSUE THREAD

**Issue by rauldds** [PRBonn/make_it_dense#6]
Hello, 

Thank you for your amazing work, it is really amazing. 

I have a few doubts and I hoped you could help me solved them (sorry if they're kind of dumb, I'm new to vdb)

First, in the script [`scan_complete.py`](https://github.com/PRBonn/make_it_dense/blob/main/src/make_it_dense/evaluation/scan_complete.py) (specifically in the function `run_tsdf`) you start to generate the tsdf grid based on a given point cloud scan. What I don't completely understand is what the `base_volume` and `target_coords_xyz_a` represent. Could you please elaborate?

Second, in the [`vdb_utils.py`](https://github.com/PRBonn/make_it_dense/blob/main/src/make_it_dense/utils/vdb_utils.py) script (specifically in the function `vdb_to_torch`) you return a dictionary with `nodes` and `origin` tensors. What do these tensors represent?

Thank you for your time. Look forward to hearing from you! :)

**Comment by nachovizzo** [comment]
@rauldds sorry for the delay!

1) As stated in the code "This is still a hack, run tsdf with a higher resolution just to obtain the target cooridnates values". I was lazy enough to compute the exact coordinates of the volumes. Taking the scan, the spatial information you can do it. I just run 1 step of tsdf and extract it with the vdb_to_numpy. This is quite awkward, but well... it does the job

2) The nodes are the leaf nodes of the VDB grid. It sounds complicated but it is always a dense voxel grid of 8x8x8 voxels. You can use the vdb visualizer to inspect those.


I hope this helps somehow!
